[project]
name = "llm-ensemble"
version = "0.0.1"
description = "CLI-first LLM ensemble relevance judging system"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pyarrow>=17.0.0",
  "pandas>=2.2.2",
  "polars>=1.5.0",
  "jinja2>=3.1.4",
  "pydantic>=2.7.4",
  "rich>=13.7.1"
]
